version: '3'
services:
  php:
    image: crispyduck/log-viewer-2-api:latest
    volumes:
      - ./api-settings-example.json:/app/settings.json
  nginx:
    # build: ../.
    image: crispyduck/log-viewer-2:latest
    ports:
      - "80:80"
    environment: 
      - ANGULAR_BASE_HREF=/logging/2/
    depends_on:
      - php